packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  react: 19.1.1
  typescript: 5.9.2
  react-dom: 19.1.1
  vite: 5.4.0
  fastify: 5.5.0
  '@apollo/server': 5.0.0
  dotenv: 17.2.1
  tslib: 2.8.1
  vitest: 2.1.1
  next: 15.5.2
